### ISSUE TITLE
Fortran error when using pymatgen version > 2018.8.7

### ISSUE THREAD

**Issue by tsthakur** [lekah/supercellor#1]
### Describe the bug

When the exact pymatgen version is not present in the python environment, trying to import anything from the supercellor library results in following error:

`~/git/ocv/supercellor/supercellor/supercell.py in <module> 6 from pymatgen.util.coord import lattice_points_in_supercell 7 ----> 8 from supercellor.lib.optimal_supercell import ( 9 utils, fort_optimal_supercell_hnf, fort_optimal_supercell_bec) 10 ImportError: /home/tthakur/git/ocv/supercellor/supercellor/lib/optimal_supercell.cpython-39-x86_64-linux-gnu.so: undefined symbol: __kmpc_begin`

The kmpc undefined symbol error seems to be a fortran compilation error when the python part of the code tries to interact with the fortran part.

### Steps to reproduce

1. Change the `setup.json` file to remove the requirement on specific pymatgen version.
2. Install normally.
3. Try to import the `supercell` class from supercellor library.

### Expected behavior

One should be able to import the library like normally without any error. It would be ideal to not have a hard requirement on a specific version of a popular python library which at this point is more than 4 years old.

### Your environment

- Operating system: Ubuntu 22.04
- Python version: 3.9.13
- pymatgen: 2022.01.09

### Additional context

It is also possible that this error is due the python version and not pymatgen version as pymatgen 2018.8.7 requires python < 3.8.

**Comment by lekah** [comment]
Does this error still persist? I cannot reproduce it. I have created a new develop branch that gets rid of this pymatgen specification and works with python 3. I have to fix a couple of tests there but I don't get an import error.

**Comment by tsthakur** [comment]
The `__kmpc_begin` error seems to point to a problem regarding Intel compilers. Since you already had GNU compilers the error couldn't be reproduced. On my end, upon installing the correct compiler with `sudo apt install gfortran` this particular problem was resolved.

However, it should be noted that there is an unexpected dependency with `setuptools`, where a version > 65.5.0 resulted in another error while doing the following import - `from distutils.log import Log as old_Log` which numpy does internally for some function. So one should be careful and keep `setuptools<=65.5`.
